### ISSUE TITLE
Is it possible to remove use of class variables in ArangoServer class?

### ISSUE THREAD

**Issue by sdalgard** [StefanoMartin/ArangoRB#4]
Hi,
I am looking into the possibility to connect my Rails server application to ArangoDb.
It is a portal storing data to multiple different ArangoDb servers.
This doesn't seem possible to do using the ArangoServer class having class variables like @@username/@@password/@@server...

I am considering forking the code and rewrite making all class variables (@@xxxx) into instance variables (@xxx).
Will this be possible or do you forsee any showstoppers making this impossible?

Thanks for any response.
Steffen Dalgard

**Comment by StefanoMartin** [comment]
Hi,
It is not impossible to make the change but it requires a discrete effort: you shall rewrite ArangoServer and the self.class.get requests in all the classes need to reference an instance method in ArangoServer. This last change need to be done since we cannot refer to the instance class of HTTParty that I am using now.

However I understand the issue and in my future release I plan to make this change. I hope to create a branch for a future release quite soon.

Best regards,
Stefano Martin

**Comment by StefanoMartin** [comment]
Now, in ArangoRB v2.0.0 is possible to create separate Arango::Server instances to supports multiple servers.
